*-----------------------------------------------------------
* GAME CONSTANTS
*-----------------------------------------------------------

;-·-·-·BULLET RELATED CONSTANT·-·-·-·-·-·-·-·-·-·-·-·-·-·-·
BULRAD      EQU     1                       ;BULLET RAD
BULPCOL     EQU     $000084BE               ;TANQUES ASESINADOS
BULFCOL     EQU     $002897C8               ;TANQUES ASESINADOS
BULSPE      EQU     3                       ;BULET SPEED




*~Font name~Courier New~
*~Font size~10~
*~Tab type~0~
*~Tab size~4~
